### ISSUE TITLE
Element patch for a critical E2EE vulnerability

### ISSUE THREAD

**Issue by eNkKVS4HxHc9jaq** [portapps/element-portable#41]
Just wanted to point out that the app should be updated to version 1.8.5 which seems to be the new release that recently patched a critical E2EE vulnerability as can be read here :

https://matrix.org/blog/2021/09/13/vulnerability-disclosure-key-sharing/

**Comment by HawkLiking** [comment]
See my pull request here: https://github.com/portapps/element-portable/pull/40

You can download the new binaries here : https://github.com/HawkLiking/element-portable/actions/runs/1230727510

**Comment by crazy-max** [comment]
Available: https://portapps.io/app/element-portable/#download
