### ISSUE TITLE
The portable version is not as fast as the installed version. When you open it.

### ISSUE THREAD

**Issue by fudilove** [portapps/element-portable#49]
The portable version is not as fast as the installed version. When you open it.
I have set it to stay in the background process after shutdown, but I still haven't installed the version fast. Obviously, slow down.

I like the portable version because it can be easily taken away with the extension.

The portable version should be faster. I don't know why?

**Comment by crazy-max** [comment]
Hard to tell without logs and repro. Please create a proper [bug report](https://github.com/portapps/element-portable/issues/new?assignees=&labels=&template=bug_report.md) and give more details. Thanks
