### ISSUE TITLE
"Missing translation" of portable Riot

### ISSUE THREAD

**Issue by MikeBlueberry** [portapps/element-portable#7]
### Behaviour
 The portable app of Riot shows a "missing translation" in all places of the interface. My IP address is Portuguese.

#### Steps to reproduce this issue
1. Install Riot's portable app by CrazyMax on portapps.io
2. Open the app
3. You'll see the "missing translation" issue

#### Expected behaviour
It should not show "missing translation".

> Tell me what should happen
It should just show the default English version, or a way to change it to another language. I'm fine with English though.

#### Actual behaviour
It should not show "missing translation".

> Tell me what happens instead
https://www.screencast.com/t/O4bNf8SxVJa

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
1.5.8-28 win64
**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10
**Winver screenshot** :
https://www.screencast.com/t/EQAVzGKcE

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.
Issue, see screenshot: https://www.screencast.com/t/O4bNf8SxVJa

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@accounts1github This issue is linked to Riot and not the portable wrapper itself. You can get support for Riot here: https://github.com/vector-im/riot-web

See also https://github.com/vector-im/riot-web/issues?utf8=%E2%9C%93&q=missing+translation
